In [34]:
import pandas as pd

In [35]:
df=pd.read_csv('customer_shopping_behavior.csv')

In [36]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [38]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [39]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [40]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x : x.fillna(x.median()))

In [41]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [42]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')

In [43]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [44]:
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [45]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [46]:
#Create a column 'age_group'
lables=['young adult','adult','middle-aged','senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=lables)
df[['age','age_group']].head(10)

   age    age_group
0   55  middle-aged
1   19  young adult
2   50  middle-aged
3   21  young adult
4   45  middle-aged
5   46  middle-aged
6   63       senior
7   27  young adult
8   26  young adult
9   57  middle-aged

In [47]:
# create new column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [48]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [49]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [50]:
df=df.drop('promo_code_used',axis=1)
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [51]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\piu chatterjee\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\piu chatterjee\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\piu chatterjee\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\piu chatterjee\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [53]:
from sqlalchemy import create_engine


# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      # default user
password = "maamaado" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "customer_behavior"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.") # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "customer_behavior"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'method'
[SQL: INSERT INTO customer (customer_id, age, gender, item_purchased, category, purchase_amount, location, size, color, season, review_rating, subscription_status, shipping_type, discount_applied, previous_purchases, payment_method, frequency_of_purchases, ... 435852 characters truncated ... ethod__999)s, %(frequency_of_purchases__999)s, %(age_group__999)s, %(purchase_frequency_days__999)s)]
[parameters: {'gender__0': 'Male', 'subscription_status__0': 'Yes', 'review_rating__0': 3.1, 'age__0': 55, 'category__0': 'Clothing', 'customer_id__0': 1, 'shipping_type__0': 'Express', 'item_purchased__0': 'Blouse', 'purchase_frequency_days__0': 14, 'color__0': 'Gray', 'season__0': 'Winter', 'payment_method__0': 'Venmo', 'age_group__0': 'middle-aged', 'discount_applied__0': 'Yes', 'location__0': 'Kentucky', 'size__0': 'L', 'previous_purchases__0': 14, 'purchase_amount__0': 53, 'frequency_of_purchases__0': 'Fortnightly', 'gender__1': 'Male', 'subscription_status__1': 'Yes', 'review_rating__1': 3.1, 'age__1': 19, 'category__1': 'Clothing', 'customer_id__1': 2, 'shipping_type__1': 'Express', 'item_purchased__1': 'Sweater', 'purchase_frequency_days__1': 14, 'color__1': 'Maroon', 'season__1': 'Winter', 'payment_method__1': 'Cash', 'age_group__1': 'young adult', 'discount_applied__1': 'Yes', 'location__1': 'Maine', 'size__1': 'L', 'previous_purchases__1': 2, 'purchase_amount__1': 64, 'frequency_of_purchases__1': 'Fortnightly', 'gender__2': 'Male', 'subscription_status__2': 'Yes', 'review_rating__2': 3.1, 'age__2': 50, 'category__2': 'Clothing', 'customer_id__2': 3, 'shipping_type__2': 'Free Shipping', 'item_purchased__2': 'Jeans', 'purchase_frequency_days__2': 7, 'color__2': 'Maroon', 'season__2': 'Spring', 'payment_method__2': 'Credit Card' ... 18900 parameters truncated ... 'item_purchased__997': 'Pants', 'purchase_frequency_days__997': 14, 'color__997': 'Cyan', 'season__997': 'Spring', 'payment_method__997': 'Cash', 'age_group__997': 'senior', 'discount_applied__997': 'Yes', 'location__997': 'Kentucky', 'size__997': 'M', 'previous_purchases__997': 31, 'purchase_amount__997': 30, 'frequency_of_purchases__997': 'Fortnightly', 'gender__998': 'Male', 'subscription_status__998': 'Yes', 'review_rating__998': 3.8, 'age__998': 51, 'category__998': 'Footwear', 'customer_id__998': 999, 'shipping_type__998': 'Next Day Air', 'item_purchased__998': 'Shoes', 'purchase_frequency_days__998': 14, 'color__998': 'White', 'season__998': 'Spring', 'payment_method__998': 'Bank Transfer', 'age_group__998': 'middle-aged', 'discount_applied__998': 'Yes', 'location__998': 'Connecticut', 'size__998': 'M', 'previous_purchases__998': 48, 'purchase_amount__998': 90, 'frequency_of_purchases__998': 'Bi-Weekly', 'gender__999': 'Male', 'subscription_status__999': 'Yes', 'review_rating__999': 2.9, 'age__999': 50, 'category__999': 'Clothing', 'customer_id__999': 1000, 'shipping_type__999': 'Standard', 'item_purchased__999': 'Socks', 'purchase_frequency_days__999': 30, 'color__999': 'Brown', 'season__999': 'Spring', 'payment_method__999': 'Debit Card', 'age_group__999': 'middle-aged', 'discount_applied__999': 'Yes', 'location__999': 'New Mexico', 'size__999': 'L', 'previous_purchases__999': 23, 'purchase_amount__999': 28, 'frequency_of_purchases__999': 'Monthly'}]
(Background on this error at: https://sqlalche.me/e/20/f405)